### ISSUE TITLE
Peupler la db: il nous faudrait un script sql pour ça (insert_data.sql)

### ISSUE THREAD

**Issue by tiagoquin** [heigvd-pro-a-06/heigvd-pro-a-06#64]

**Comment by tiagoquin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [insert_data.sql : peupler la db avec un script pour les tests](https://trello.com/c/3Cf2WvkF/105-insertdatasql-peupler-la-db-avec-un-script-pour-les-tests)

**Comment by tiagoquin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Peuple la db avec des données de test. Script de remplissage](https://trello.com/c/k2jI3YyL/54-peuple-la-db-avec-des-donn%C3%A9es-de-test-script-de-remplissage)

**Comment by CrescenceK** [comment]
i'm working on it

**Comment by AlexandreGabrielli** [comment]
Done
